"""Markdown branding helpers for exported reports."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any


PRODUCT_NAME = "ScholarLint · 投稿通"
WEBSITE_URL = "https://scholarlint.com"
DISCLAIMER_TEXT = "自动化检查不等于录用保证；引文、数据与科学结论需人工核实。"
CTA_TEXT = "访问 ScholarLint · 投稿通 官网了解投稿前检查工作流。"
AUTHOR_REPORT_TYPE = "作者工作区版"
SHARE_REPORT_TYPE = "导师只读分享版"


def _strip_fractional_seconds(value: str) -> str:
    return re.sub(r"(?<=\d{2}:\d{2}:\d{2})\.\d+", "", value)


def _format_utc(value: datetime | str) -> str:
    """Return a stable UTC-ish string for Markdown report metadata."""
    if isinstance(value, datetime):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")

    text = value.strip()
    try:
        parsed = datetime.fromisoformat(text[:-1] + "+00:00" if text.endswith("Z") else text)
    except ValueError:
        return _strip_fractional_seconds(value)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def report_type_label(via_share: bool) -> str:
    """Name the export mode shown in the report."""
    return SHARE_REPORT_TYPE if via_share else AUTHOR_REPORT_TYPE


def build_report_header(
    report: Any,
    job_id: str,
    *,
    exported_at: datetime | str,
    via_share: bool,
    app_version: str | None = None,
) -> str:
    """Build the branded Markdown header for an exported report."""
    lines = [
        f"# {PRODUCT_NAME} — 论文完整性检查报告",
        "",
        "| 项目 | 详情 |",
        "|------|------|",
        f"| 报告 ID | `{job_id}` |",
        f"| 报告类型 | {report_type_label(via_share)} |",
        f"| 文件 | {report.filename} |",
        f"| 检查时间 | {_format_utc(report.timestamp)} |",
        f"| 导出时间 | {_format_utc(exported_at)} |",
        f"| 官网 | {WEBSITE_URL} |",
    ]
    if app_version:
        lines.append(f"| 应用版本 | {app_version} |")
    lines.extend([
        "",
        f"> 免责声明：{DISCLAIMER_TEXT}",
        "",
        f"> {CTA_TEXT} {WEBSITE_URL}",
        "",
    ])
    return "\n".join(lines)


def build_report_footer(*, via_share: bool, app_version: str | None = None) -> str:
    """Build the branded Markdown footer for an exported report."""
    lines = [
        "---",
        "",
        f"*Generated by {PRODUCT_NAME} | {WEBSITE_URL}*",
    ]
    if app_version:
        lines.append(f"*Version: {app_version}*")
    lines.extend([
        "",
        f"*报告类型：{report_type_label(via_share)}*",
        "",
        f"*免责声明：{DISCLAIMER_TEXT}*",
        "",
        "*此报告供导师/作者审核使用。标记为 ⚠️ 的项目需要人工确认。*",
    ])
    return "\n".join(lines)
